### ISSUE TITLE
Wrong icons for sizes

### ISSUE THREAD

**Issue by tsujan** [lxde/libqtxdg#122]
Consider an icon theme whose icons are all SVG and whose index contains these keys:
````
...
[places/16]
Size=16
Context=Places
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/scalable]
Size=96
Context=Places
Type=Scalable
MinSize=16
MaxSize=512
...

````
With this arrangement, KDE correctly shows the folder icon from `places/scalable` for folders ≥ 32px while LXQt gets the folder icon from `places/16` for all sizes ≥ 32px.

**Comment by tsujan** [comment]
The issue happens with the latest github version (clean and without any patch).

The problem does NOT exists in an older version from 2016-12-15 (which I had by chance).

**Comment by tsujan** [comment]
[This](https://www.dropbox.com/s/qlsoxcb98f4m9uv/xdgiconloader.cpp.diff?dl=0) is the diff for `xdgiconloader.cpp` between github and 2016-12-15.

**Comment by tsujan** [comment]
OK, the problem is in using expressions like `if (QFile::exists(pngPath))` instead of the old ones like `if (currentDir.exists(pngIconName))` in `XdgIconLoader::findIconHelper()`. Apparently, the new calculations by adding `QLatin1Char('/')` are incorrect.

Sorry, I didn't have time to see which commit was responsible!

**Comment by palinek** [comment]
> Apparently, the new calculations by adding QLatin1Char('/') are incorrect.

No, the problem is/are wrongly placed `break`(s)... see #123
