### ISSUE TITLE
Magnet links can't open currently associated application

### ISSUE THREAD

**Issue by fulalas** [lxde/libqtxdg#129]
I'm not sure if this is the right section.

Magnet links opened from inside the browser don't open Transmission Qt. I put this inside '/usr/share/applications/mimeinfo.cache':
```
[MIME Cache]
x-scheme-handler/magnet=transmission-qt.desktop;
```

And this inside '/usr/local/share/applications/defaults.list':
```
[Default Applications]
x-scheme-handler/magnet=transmission-qt.desktop;
```

It's important to notice that 'transmission-qt.desktop' exists and it's pointing to the right exec command. Also, Transmission Qt is working fine and it downloads magnets link if you paste inside it manually

**Comment by tsujan** [comment]
@palinek, @luis-pereira 

I think here is a good place to bring up a more general issue: **There's a problem with scheme handlers in LXQt.**

The same issue @fulalas has with magnet I have with `mailto`: it never opens Thunderbird but always Qupzilla. I added
```
x-scheme-handler/mailto=thunderbird.desktop;
```
to all places possible (~/.config/lxqt-mimeapps.list, ~/.config/mimeapps.list, ~/.local/share/applications/mimeapps.list) to no avail, so I stopped using it 2 years ago and forgot to look into it or even report it (there were more important issues those days).

That's while `mailto` works OK with KDE. Also `xdg-email` correctly opens Thunderbird. Only LXQt has problem.

[Elsewhere](https://github.com/lxde/lxqt/issues/1111), I discussed that `perl-file-mimeinfo` is needed by LXQt for opening links correctly. However. it seems that `perl-file-mimeinfo` is not enough in some cases.

**Comment by fulalas** [comment]
Nice information, tsujan!

I would like to add that Firefox detects Transmission Qt and asks for opening magnet links with it, but Chrome-based browsers (Chromium and Opera, so far) just open a new tab.

Also, .m3u files (Winamp list type, used among so many audio/video players, like Vlc, Qmmp and SMPlayer) have a similar behavior: double-click on them from Pcmanfm-qt and nothing happens.

**Comment by tsujan** [comment]
Oh, I forgot to confirm @fulalas's report. Because of that issue, I always drag and drop magnets into qBittorrent. Under KDE, they're correctly opened when they're clicked.

@fulalas, I think your problem with audio/video players is quite different.

(1) Have you added associations? You could use `Configuration Center` → `File Associations` or add them directly to `~/.config/mimeapps.list` (don't use `~/.local/share/applications/mimeapps.list`).

(2) Have you installed `libfile-mimeinfo-perl` (on Debian based systems) or `perl-file-mimeinfo` (on Arch based ones)?

**Comment by fulalas** [comment]
1- The way I did ('/usr/share/applications/mimeinfo.cache' and '/usr/local/share/applications/defaults.list'), when I open File Associations dialog, I see this: http://img.photobucket.com/albums/v256/Delerue/fileassociations_zpst0bfm7co.png

As you can see, there are 2 sections regarding m3u files. The second one (x-mpegurl) is already set to Qmmp. The first one (vnd.apple...?) isn't.

In a nutshell: this way it doesn't open Qmmp when I double-click a m3u file.

1.1- I would like to point to another little bug inside File Associations: if you add a new association, the dialog isn't refreshed, so you need to click on another file type and click again on the first one to see the changes.

2- I'm not sure. I'm using Porteus, which is derived from Slackware. Any suggestion?

**Comment by tsujan** [comment]
> In a nutshell: this way it doesn't open Qmmp when I double-click a m3u file.

Please forget about `/usr/share/applications/` and `~/.local/share/applications/`; especially the first one: it shouldn't be edited by users. Use `~/.config/mimeapps.list` instead -- create it if it doesn't exist and add associations to it.

`perl-file-mimeinfo` seems to be `perl-file-mimeinfo` in [Slackware](https://slackware.pkgs.org/14.1/slackonly-x86_64/perl-file-mimeinfo-0.27-x86_64-8_slack.txz.html).

Please let this report remain for `x-scheme-handler`.

If your problem with file associations isn't solved after doing what I said above, please first search for an open issue about it and add a comment; if there's no open issue, you could open one. However, I'm pretty sure that LXQt has no problem with file association. Its problem is only with scheme handlers.

**Comment by tsujan** [comment]
BTW, we'd be grateful if you report the refresh problem too but not against pcmanfm-qt.

**Comment by fulalas** [comment]
OK, I tried what you said (and it fixed .webp files not being opened by LXImage-qt, thanks) but the problem with .m3u files remains -- it simply doesn't open anything unless you right-click and 'Open with...'. :(

>BTW, we'd be grateful if you report the refresh problem too but not against pcmanfm-qt (report it here).

It seems there is no 'issue' section on LXQt-Config page: https://github.com/lxde/lxqt-config/

**Comment by tsujan** [comment]
For m3u files , I have:
```
[Added Associations]
...
audio/x-mpegurl=smplayer.desktop;vlc.desktop;featherpad.desktop;
...
[Default Applications]
...
audio/x-mpegurl=smplayer.desktop
...
```
in `~/.config/mimeapps.list`.

**Comment by tsujan** [comment]
> It seems there is no 'issue' section on LXQt-Config page

Issues can be opened at https://github.com/lxde/lxqt/issues

**Comment by fulalas** [comment]
OK, after a deeper investigation I finally began to understand the bug. The problem is a combination of 2 things, none of them related to mime stuff:

1- if the m3u file is inside a FAT/NFTS partition (it's always marked as executable and apparently you can't change this);
2- if Pcmanfm-qt preferences dialog has checked 'Don't ask options on launch executable file';

When these 2 things are set you won't be able to open a m3u file, since LXQt will try to execute it instead of opening it. So either you move your m3u files to a Linux partition (and change to non-executable) or uncheck Pcmanfm-qt 'Don't ask options on launch executable file'.

None of these solutions sound reasonable to me. Do you have a better solution?

**Comment by tsujan** [comment]
All of my partitions are ext4 and even when I make an m3u file executable (which is meaningless), pcmanfm-qt correctly opens it with the associated media player when I choose "Open". As you said, your problem is with NTFS, not with mime.

*Please be specific when reporting a bug*, otherwise a lot of time and energy would be wasted!

**Comment by fulalas** [comment]
Except that this m3u bug is secondary. The main reason this issue was opened is because of x-scheme-handler, specifically with magnet links. Do you think that I wasn't clear regarding this main bug? :(

**Comment by tsujan** [comment]
> Do you think that I wasn't clear regarding this main bug? 

I meant the second bug you included in this report, of course. We had a long discussion about it to no avail -- as we had at https://github.com/lxde/pcmanfm-qt/issues/487 -- just because some important facts weren't stated.

**Comment by fulalas** [comment]
I'm sorry, but users don't have all the knowledge you expect them to have. This one regarding m3u files was very specific and I bet even you wasn't aware of it entirely.

All debate is valid. Living and learning. :+1:

**Comment by tsujan** [comment]
> users don't have all the knowledge you expect them to have.

We really don't expect users to have any knowledge about programming. What we *prefer* is a bug report that contains specific info because otherwise false problems would be created.

> This one regarding m3u files was very specific

Not at all, unless, even now, you haven't stated it clearly. As far as I understood, it was only about files on an *NTFS partition*. It wouldn't require any knowledge to include that part in the report -- and it would make a great difference.

Anyhow, being specific is not an expectation but a request that if met, good things could happen.

**Comment by tsujan** [comment]
To be as clear as possible, if in https://github.com/lxde/pcmanfm-qt/issues/487, you just mentioned that there was *a dialog*, many things would be clear from the start. I hope you'll report bugs that we don't know about; I just like to see more specific reports from you -- like this one, except for the m3u part. Actually, on this page, you could see how good a clear report is.

**Comment by tsujan** [comment]
I opened https://github.com/lxde/pcmanfm-qt/issues/492, which is related to your m3u problem but your problem has another side too, i.e. files are excuatable on your NTFS partition. This part shouldn't be about LXQt but, perhaps, about how that NTFS partition is mounted.

If those files are NOT seen as executable files by another file manager, please open an issue with a title like "pcmanfm-qt sees all files executable on NTFS partitons". Sorry, I can't have any NTFS partition!

**Comment by luis-pereira** [comment]
@fulalas Which browser are you using ?

**Comment by luis-pereira** [comment]
Chrome/Chromium uses, AFAIK, xdg-open to find which application to use.
To check what application is the current default use:
`xdg-mime query default x-scheme-handler/magnet`

To set it, use:
`xdg-mime default transmission-qt.desktop x-scheme-handler/magnet`

**Comment by tsujan** [comment]
@luis-pereira 
As for mailto, `xdg-mime query default x-scheme-handler/mailto` gives `thunderbird.desktop` here and, as I said above, `xdg-email` gracefully opens Thunderbird email composing page but mailto links are wrongly  "opened" by Qupzilla.

**Comment by fulalas** [comment]
@luis-pereira, I'm using Opera (Chromium-based). If I execute the first command you told me this is what terminal prints:
`transmission-qt.desktop`

And if I execute the second command I receive this:
```
touch: cannot touch '/home/guest/.local/share/applications/mimeapps.list': No such file or directory
/usr/bin/xdg-mime: line 827: /home/guest/.local/share/applications/mimeapps.list.new: No such file or directory
```
Then I made a copy of my mimeapps to '/home/guest/.local/share/applications/' and execute the second command again, receiving no output whatsoever. Unfortunately the problem remains: clicking on a magnet link inside Opera/Chromium simply opens a new tab instead of Transmission Qt. :(

**Comment by fulalas** [comment]
I've finally managed to fix it. It seems to be a problem with xdg-open, not LXQt, although maybe LXQt can handle this somehow.

References:
https://translate.google.com/translate?depth=1&hl=id&ie=UTF8&nv=1&prev=_m&rurl=translate.google.co.id&sl=auto&sp=nmt4&tl=en&u=https://ziggi.org/chromium-ne-otkryvaet-magnet-steam-i-drugie-podobnye-ssylki/

https://github.com/ziggi/xdg-utils-patched/blob/master/generic_x_scheme.patch

**Comment by tsujan** [comment]
At least for mailto, I see the problem as an LXQt bug because mailto works OK with KDE.

**Comment by fulalas** [comment]
I don't know. Maybe KDE handle this problem.

**Comment by tsujan** [comment]
> I don't know. Maybe KDE handle this problem.

Then LXQt should do so too. My point: this *is* a bug.

**Comment by luis-pereira** [comment]
@tsujan If xdg-open does the correct thing, it's not a LXQt bug but rather someone else's bug that LXQt should fix.
Consider this, under LXQt:
`xdg-open 'magnet:?xt=urn:ed2k:354B15E68FB8F36D7CD88FF94116CDC1&xt=urn:tree:tiger:7N5OAMRNGMSSEUE3ORHOKWN4WWIQ5X4EBOOTLJY&xt=urn:btih:QHQXPYWMACKDWKP47RRVIV7VOURXFE5Q&xl=10826029&dn=mediawiki-1.15.1.tar.gz&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&as=http%3A%2F%2Fdownload.wikimedia.org%2Fmediawiki%2F1.15%2Fmediawiki-1.15.1.tar.gz&xs=http%3A%2F%2Fcache.example.org%2FXRX2PEFXOOEJFRVUCX6HMZMKS5TWG4K5&xs=dchub://example.org'
`
it opens a new instance of chromium.
now do:
`export DE="xfce"`
and repeat the above command. In my system ir correctly open transmission.
@tsujan The real issue here is that xdg only recognizes: gnome, kde, xfce, lxde and mate.

I remember that a try was made to include lxqt in the list. But without success. Will try to find it.

**Comment by tsujan** [comment]
> @tsujan The real issue here is that xdg only recognizes: gnome, kde, xfce, lxde and mate.

Yes, this is what I also concluded a year ago. If lxde is recognized, lxqt should be included too.

Here, I was hoping for a workaround. If I said it was an LXQt bug, I meant it on the UX level -- but you're right, on the technical level.

**Comment by luis-pereira** [comment]
@tsujan 
Update:
The latest git already as some LXQt support, see commit https://cgit.freedesktop.org/xdg/xdg-utils/commit/?id=6387086e4938d568c2bab185632f60e1619b3f68.

Didn't install it yet. But, by looking at the source.... it probably works.

**Comment by tsujan** [comment]
@agaida that's good news.

**Comment by luis-pereira** [comment]
@tsujan @agaida @fulalas The latest git xdg-utils actually correctly open magnet links from chromium.
Awesome news.

**Comment by tsujan** [comment]
Ah, at last! mailto is fixed too :) Glad to see that both LXQt and Enlightenment are recognized!

@luis-pereira, thanks for the info!

This can be closed because, sooner or later, the git `xdg-utils` will come to all distros.

**Comment by tsujan** [comment]
Actually, xdg-utils 1.1.2 is a mess regarding LXQt: although magnet and mailto are fixed, xdg-open thinks that all links starting with `file://` (for example, `fie:///.../XXX.pdf`) should be opened by pcmanfm (and not even pcmanfm-qt) under LXQt. Shouldn't we tell them about that?

**Comment by agaida** [comment]
we should, it's boring

**Comment by tsujan** [comment]
> we should, it's boring

I agree. Fortunately, 1.1.2 isn't released yet.

Let me explain the problem:

The fact that pcmanfm-qt opens files with their corresponding apps doesn't prove that xdg-utils is OK. Qt has the static method `QDesktopServices::openUrl()`, which can be used to know if xdg-utils works fine under a DE.

With xdg-utils 1.1.1 and if `perl-file-mimeinfo` is installed, `QDesktopServices::openUrl()` opens all URLs correctly. With xdg-utils 1.1.2, it tries to open all `file:///...` URLs with pcmanfm -- because xdg-utils wants to do so -- and therefore, it fails.

**Comment by tsujan** [comment]
The disaster happened; xdg-utils 1.1.2 came to Arch (and Manjaro) with its LXQt-friendly appearance. I have to change:
```shell
    lxde|lxqt)
    open_lxde "$url"
    ;;
```
to
```shell
    lxde|lxqt)
    open_generic "$url"
    ;;
```
in `/usr/bin/xdg-open` for `xdg-open` to open a pdf file correctly under LXQt, for example!! Without this change, it gives this error message:
````
/usr/bin/xdg-open: line 922: pcmanfm: command not found
````
Please tell them (I would if I knew of the best way to do it)!

**Comment by tsujan** [comment]
Opened https://github.com/lxde/lxqt/issues/1298
