### ISSUE TITLE
xdg-mime query default inode/directory returns wrong result

### ISSUE THREAD

**Issue by damonlynch** [lxde/libqtxdg#134]
```
$ xdg-mime query default inode/directory
nautilus-folder-handler.desktop
```
I assume the correct result for now would be `pcmanfm.desktop`

**Comment by palinek** [comment]
Hi, `xdg-mime` has nothing to do with `libqtxdg`, it's a part of the [xdg-utils project](https://www.freedesktop.org/wiki/Software/xdg-utils/).

**Comment by damonlynch** [comment]
So where do I file a bug report for Lubuntu next? I thought that's what I was doing here.

**Comment by palinek** [comment]
> So where do I file a bug report for Lubuntu next? I thought that's what I was doing here.

IMO here: https://bugs.launchpad.net/lubuntu-next/+filebug

**Comment by tsimonq2** [comment]
@damonlynch Hey, Release Manager of Lubuntu here, thanks for trying out Lubuntu Next. :)

@palinek is correct, that's a good place to report the bug.

Thanks!

**Comment by agaida** [comment]
and there is not much one can do about the mime-type settings - eventually setting the mime-types in the user will help - until the next application comes around and think it is cool to take over several mime-types. 

We could consider the mime-handling some kind of broken - and to make things worse there are some  other things involved in finding the right mime-type. As i wrote, when things like that, the simpel solution is to use some swear words and override it locally.
