### ISSUE TITLE
Use QStandardPaths where possible.

### ISSUE THREAD

**Issue by luis-pereira** [lxde/libqtxdg#38]
Based on part of https://github.com/lxde/libqtxdg/pull/6

**Comment by jleclanche** [comment]
@luis-pereira Is this possible before 0.9?

**Comment by jleclanche** [comment]
@luis-pereira status on this? Are you still on it or can someone else take it?

**Comment by paulolieuthier** [comment]
@luis-pereira describe what this is about and someone may be work on it.

**Comment by luis-pereira** [comment]
@jleclanche @paulolieuthier I'm on it already.

**Comment by paulolieuthier** [comment]
Great.

**Comment by luis-pereira** [comment]
Closed by https://github.com/lxde/libqtxdg/commit/93bc5207b8750fe3e70236ee98dea6c5aca4a3e2
