### ISSUE TITLE
Qt4 build failing due to missing Qt5X11Extras

### ISSUE THREAD

**Issue by novist** [lxde/libqtxdg#43]
Build fails because it can not find Qt5X11Extras package even though lxqt is being built with qt4.

	Building: libqtxdg using externally specified options: -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/storage/src/lxqt-build  

	-- Building with Qt 4.8.6
	-- qtxdg: writing pkgconfig file /storage/src/lxqt/libqtxdg/build/qtxdg.pc
	-- 
	-- For building tests use -DBUILD_TESTS=Yes option.
	-- 
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /storage/src/lxqt/libqtxdg/build
	Scanning dependencies of target qtxdg
	[  3%] [  7%] [ 10%] [ 14%] [ 17%] [ 21%] [ 25%] [ 28%] Building CXX object CMakeFiles/qtxdg.dir/xdgaction.cpp.o
	Building CXX object CMakeFiles/qtxdg.dir/xdgdesktopfile.cpp.o                                                                                                          
	Building CXX object CMakeFiles/qtxdg.dir/xdgmenu.cpp.o                                                                                                                 
	Building CXX object CMakeFiles/qtxdg.dir/xdgmenureader.cpp.o                                                                                                           
	Building CXX object CMakeFiles/qtxdg.dir/xdgicon.cpp.o                                                                                                                 
	Building CXX object CMakeFiles/qtxdg.dir/xdgmenuapplinkprocessor.cpp.o                                                                                                 
	Building CXX object CMakeFiles/qtxdg.dir/xdgdirs.cpp.o                                                                                                                 
	Building CXX object CMakeFiles/qtxdg.dir/xdgmenulayoutprocessor.cpp.o                                                                                                  
	[ 32%] Building CXX object CMakeFiles/qtxdg.dir/xdgmenurules.cpp.o                                                                                                     
	[ 35%] Building CXX object CMakeFiles/qtxdg.dir/xdgmenuwidget.cpp.o                                                                                                    
	[ 39%] Building CXX object CMakeFiles/qtxdg.dir/xmlhelper.cpp.o                                                                                                        
	[ 42%] Building CXX object CMakeFiles/qtxdg.dir/xdgautostart.cpp.o                                                                                                     
	[ 46%] Building CXX object CMakeFiles/qtxdg.dir/qiconfix/qiconloader_qt4.cpp.o                                                                                         
	[ 50%] Building CXX object CMakeFiles/qtxdg.dir/xdgmimetype.cpp.o                                                                                                      
	[ 53%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgaction.cxx.o                                                                                                    
	[ 57%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgmenuapplinkprocessor.cxx.o                                                                                      
	[ 60%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgmenu.cxx.o                                                                                                      
	[ 64%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgmenu_p.cxx.o                                                                                                    
	[ 67%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgmenureader.cxx.o                                                                                                
	[ 71%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgmenurules.cxx.o                                                                                                 
	[ 75%] Building CXX object CMakeFiles/qtxdg.dir/moc_xdgmenuwidget.cxx.o                                                                                                
	Linking CXX shared library libqtxdg.so
	[100%] Built target qtxdg
	[100%] Built target qtxdg
	Install the project...
	-- Install configuration: "debug"
	-- Installing: /storage/src/lxqt-build/lib/x86_64-linux-gnu/libqtxdg.so.1.0.0
	-- Up-to-date: /storage/src/lxqt-build/lib/x86_64-linux-gnu/libqtxdg.so.1
	-- Up-to-date: /storage/src/lxqt-build/lib/x86_64-linux-gnu/libqtxdg.so
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgaction.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgdesktopfile.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgdirs.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgicon.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgmenu.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgmenuwidget.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xmlhelper.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgautostart.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgmacros.h
	-- Up-to-date: /storage/src/lxqt-build/include/qtxdg/xdgmimetype.h
	-- Installing: /storage/src/lxqt-build/share/cmake/qtxdg/qtxdg-config.cmake
	-- Up-to-date: /storage/src/lxqt-build/share/cmake/qtxdg/qtxdg_use.cmake
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgAction
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgDesktopFile
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgDirs
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgIcon
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgMenu
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgMenuWidget
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XmlHelper
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgAutoStart
	-- Installing: /storage/src/lxqt-build/include/qtxdg/XdgMimeType
	-- Installing: /storage/src/lxqt-build/lib/x86_64-linux-gnu/pkgconfig/qtxdg.pc

	Building: liblxqt using externally specified options: -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=/storage/src/lxqt-build  

	CMake Error at CMakeLists.txt:130 (find_package):
	By not providing "FindQt5X11Extras.cmake" in CMAKE_MODULE_PATH this project
	has asked CMake to find a package configuration file provided by
	"Qt5X11Extras", but CMake did not find one.

	Could not find a package configuration file provided by "Qt5X11Extras" with
	any of the following names:

		Qt5X11ExtrasConfig.cmake
		qt5x11extras-config.cmake

	Add the installation prefix of "Qt5X11Extras" to CMAKE_PREFIX_PATH or set
	"Qt5X11Extras_DIR" to a directory containing one of the above files.  If
	"Qt5X11Extras" provides a separate development package or SDK, be sure it
	has been installed.

	-- Configuring incomplete, errors occurred!
	See also "/storage/src/lxqt/liblxqt/build/CMakeFiles/CMakeOutput.log".

**Comment by jleclanche** [comment]
Uh, that's liblxqt, not libqtxdg. And liblxqt doesn't support qt4 anymore.
