### ISSUE TITLE
XdgDesktopFile: Not executing Type=Application with pkexec on the Exec line

### ISSUE THREAD

**Issue by luis-pereira** [lxde/libqtxdg#50]
The use of ```QProcess::startDetached()``` in ```XdgDesktopFile::startDetached()``` makes pkexec exit with "Refusing to render service to dead parents." due to double forking. http://cgit.freedesktop.org/polkit/tree/src/programs/pkexec.c#n730

References:
https://issues.openmandriva.org/show_bug.cgi?id=1128#c3

**Comment by palinek** [comment]
I don't know how the ```XdgAction``` or ```XdgDesktopFile``` are used (if the calling/executin application can finish etc..), but I had a quick look at this and the solution for pkexec can be something like this:
```c++
QProcess* p = new QProcess;
p->setStandardInputFile(QProcess::nullDevice());
//XXX: we probably should redirect stdout/stderr to our stdout/stderr
p->setStandardOutputFile(QProcess::nullDevice());
p->setStandardErrorFile(QProcess::nullDevice());
connect(p, &QProcess::finished, p, &QObject::deleteLater);
p->start(cmd, args);
return p->waitForStarted();
```

**Comment by palinek** [comment]
Just played with this one and IMO there is no "easy & nice" solution. Following is possible:

1. use the above, but the newly spawned process remains a direct child of the parent process (lxqt-runner, lxqt-panel ... etc) => if the parent process ends, the child exits also (gets a SIGHUP)

2. if we want to completely detach from parent process we must implement our wrapper which would completely detach from parent (two ```fork```s, ```setsid```... etc), after that spawns required child (```exec```) and just wait for it's exit => all created process's will have dumb running parent process

3. use the above only as a workaround for ```pkexec``` (or any other known in the future)

**Comment by palinek** [comment]
Sorry for misleading with the above... all that is true only in case the parent process has a tty attached. That's not the case of lxqt components run by DM.
Just tried the above solution with lxqt-panel (with no tty) => pkexec (in .desktop) works and application spawned by lxqt-parent don't exit upon killing lxqt-panel.

... will make PR

@paulolieuthier the ```QProcess::startDetached``` is also used in lxqt-runner so running "pkexec <application>" don't work either there. Maybe we should use this solution also there...
