### ISSUE TITLE
Improve icon lookup performance

### ISSUE THREAD

**Issue by luis-pereira** [lxde/libqtxdg#56]
The icon lookup algorithm  works by always looking up filenames in directories (stat). The goal here is implement a caching mechanism to reduce the number of required stat's lookup an icon.

I already started doing it :smile:

**Comment by paulolieuthier** [comment]
I few numbers from callgrind:

I got more than 40K calls to `QDir::exists` in a few seconds running lxqt-panel. More than 30K of that is from `QtXdg::QIconLoader::findIconHelper`. More than 10K from Qt's own `QIconLoader::findIconHelper`.

**Comment by paulolieuthier** [comment]
I'm not sure if, in the POV of LXQt, that cache would still make sense when LXQt's own also-yet-to-be-done icon caching is implemented. What do you think?

**Comment by luis-pereira** [comment]
@paulolieuthier Not sure I understood your question.
I made some efforts in caching the icon filenames as suggested in the freedesktop specification. It cuts down the lookup overheads you find. 
What's missing is an system-wide cache container. KDE has one that seems to fit my intents.

**Comment by paulolieuthier** [comment]
This system-wide cache could be implemented in libqtxdg? IMO it only makes sense in the Qt plugin. That's what I meant.

**Comment by luis-pereira** [comment]
system-wide was a not so good name choice. `XdgIcon` system-wide cache is more acurate.
I did not thought on how to do it.

**Comment by luis-pereira** [comment]
Commit https://github.com/lxde/libqtxdg/commit/81112762d6a74bd8188acf00d7a6469f5541e035 is a good way to solve this, IMO.

**Comment by luis-pereira** [comment]
Commit 81112762d6a74bd8188acf00d7a6469f5541e035 improves the lookup performance. Closing.
