### ISSUE TITLE
Clarify license of certain files for Debian packaging

### ISSUE THREAD

**Issue by czchen** [lxde/libqtxdg#59]
We need to clarify the license of all files to make this library into Debian. Please help to add license header for the following files:

desktopenvironment_p.cpp: *No copyright* UNKNOWN
test/qtxdg_test.cpp: *No copyright* UNKNOWN
test/qtxdg_test.h: *No copyright* UNKNOWN
xdgdesktopfile_p.h: *No copyright* UNKNOWN

**Comment by palinek** [comment]
@luis-pereira I didn't notice...you've been selfassigned ...

**Comment by luis-pereira** [comment]
@palinek no problem. I love done work. Merge it, pls.

**Comment by jleclanche** [comment]
@agaida @luis-pereira We should do a separate license cleanup for libqtxdg too.

**Comment by agaida** [comment]
full ack
