### ISSUE TITLE
Empty menu when XDG_DATA_DIRS is not

### ISSUE THREAD

**Issue by plfiorini** [lxde/libqtxdg#62]
When I run Hawaii and XDG_DATA_DIRS is empty I don't see the menu.
I believe that libqtxdg should assume a default as said by the specification [1].
Setting XDG_DATA_DIRS make it work.

[1] = http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by luis-pereira** [comment]
@plfiorini I can't debug it right now. libqtxdg follows the specification. See [here](https://github.com/lxde/libqtxdg/blob/master/xdgdirs.cpp#L239)
An bug is always an possibility tough.

**Comment by luis-pereira** [comment]
Update:
```
[lpereira ~/lxqt/lxqt-github/libqtxdg/examples/use-qtxdg/build (master)]$ env | grep XDG_DATA_DIRS                                                              
[lpereira ~/lxqt/lxqt-github/libqtxdg/examples/use-qtxdg/build (master)]$ ./use-qtxdg                                                                           
("/usr/local/share", "/usr/share") 
```

@plfiorini It's assuming the default as said by specification.

**Comment by plfiorini** [comment]
The code that sets defaults was introduced by this commit
https://github.com/lxde/libqtxdg/commit/dcfb0dc4aa61c7a6f5d5746e46cfb7fa40272e95

My distro has libqtxdg 1.2.0 released in March (if I'm not mistaken) so maybe that commit is missing.

**Comment by luis-pereira** [comment]
@plfiorini Yeap, That's it.
