### ISSUE TITLE
Enable GitHub wiki for this repository

### ISSUE THREAD

**Issue by SuicSoft** [lxde/libqtxdg#71]

**Comment by palinek** [comment]
@luis-pereira @jleclanche ?

**Comment by pmattern** [comment]
Wouldn't it eventually be better if we kept all wiki articles summarized in the wiki of component "lxqt" (https://github.com/lxde/lxqt/wiki)? So far no single wiki article exists outside that wiki (besides some components do have their own wiki enabled).

**Comment by jleclanche** [comment]
I explicitly disabled the wiki because sharding the lxqt components' wikis is very unnecessary.

If you want to contribute docs, I'd say contributing a docs/ folder in the repo itself would be more useful.

**Comment by SuicSoft** [comment]
Ok
