### ISSUE TITLE
"files in some directories may conflict with libraries in implicit directories"

### ISSUE THREAD

**Issue by r-a-v-a-s** [lxde/libqtxdg#89]
When using cmake:

```
CMake Warning at qtxdg/CMakeLists.txt:68 (add_library):
  Cannot generate a safe runtime search path for target Qt5Xdg because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libQt5Widgets.so.5] in /usr/lib64 may be hidden by files in:
      /home/styling/Qt/5.6/gcc_64/lib
    runtime library [libQt5Xml.so.5] in /usr/lib64 may be hidden by files in:
      /home/styling/Qt/5.6/gcc_64/lib
    runtime library [libQt5Gui.so.5] in /usr/lib64 may be hidden by files in:
      /home/styling/Qt/5.6/gcc_64/lib
    runtime library [libQt5Core.so.5] in /usr/lib64 may be hidden by files in:
      /home/styling/Qt/5.6/gcc_64/lib

  Some of these libraries may not be found correctly.
```

Then with make

```
[  3%] Building CXX object xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o
In file included from /home/styling/repositories/libqtxdg/xdgiconloader/xdgiconloader.cpp:34:0:
/home/styling/repositories/libqtxdg/xdgiconloader/xdgiconloader_p.h:56:29: fatal error: private/qicon_p.h: No such file or directory
compilation terminated.
xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/build.make:62: recipe for target 'xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o' failed
make[2]: *** [xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/xdgiconloader.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/all' failed
make[1]: *** [xdgiconloader/CMakeFiles/Qt5XdgIconLoader.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

I couldn't figure out what to do about it.

The Qt version in /home was installed for other projects via:
https://wiki.qt.io/Install_Qt_5_on_openSUSE

I'm on openSUSE Tumbleweed.

**Comment by luis-pereira** [comment]
@r-a-v-a-s libqtxdg had recently changes in it's internal organization. Pls make sure that you start with a clean build dir.
If the issue persists I will need more info:

- CMake version
- verbose build log
- CMake Generator

**Comment by r-a-v-a-s** [comment]
I cloned the repository two days ago; therefore, the build directory was clean.

cmake-3.5.2-253.3.x86_64

I don't know how to provide the other information.

**Comment by luis-pereira** [comment]
Are you using make, ninja, etc etc as an build generator ?

**Comment by r-a-v-a-s** [comment]
I used `make`

**Comment by luis-pereira** [comment]
Run:
```
cmake ..
make VERBOSE=1
```

and post the results. Use pastebin or something like that.

**Comment by r-a-v-a-s** [comment]
http://pastebin.com/949VMzgH

**Comment by luis-pereira** [comment]
How many Qt versions do you have installed ?
The link talks about Qt 5.4.1 on openSUSE 13.2. In the logs cmake seems to have found Qt 5.6.0.
What about the `cmake ..` output ?

**Comment by r-a-v-a-s** [comment]
I have only ever installed 5.6.0... plus whatever comes with openSUSE / KDE and lxqt

The full cmake output is in my first post.

**Comment by r-a-v-a-s** [comment]
Actually I missed the first line `Building with Qt 5.6.0`

**Comment by luis-pereira** [comment]
Where is Qt 5.6.0 installed ?

**Comment by r-a-v-a-s** [comment]
Because I was not instructed otherwise, I installed it to the default location (/home/username/Qt).

**Comment by luis-pereira** [comment]
@r-a-v-a-s What's the output of `qtdiag` ?

**Comment by r-a-v-a-s** [comment]
http://pastebin.com/8i4YsXeG

**Comment by luis-pereira** [comment]
@r-a-v-a-s Uninstall the stuff you have at ` /home/styling/Qt` and start again with an empty build dir.

**Comment by r-a-v-a-s** [comment]
Cmake seems to run fine... but I get the same output for make.

**Comment by r-a-v-a-s** [comment]
Looking at the make output:
`-I/usr/include/qt5/QtGui/5.6.0 -I/usr/include/qt5/QtGui/5.6.0/QtGui -I/usr/include/qt5/QtCore/5.6.0 -I/usr/include/qt5/QtCore/5.6.0/QtCore -`

I have usr/include/qt5/QtCore and /QtGui but they don't have a 5.6.0 folder in them.

**Comment by luis-pereira** [comment]
@r-a-v-a-s But you should have. That's something wrong with your Qt deployment.

**Comment by r-a-v-a-s** [comment]
https://forums.opensuse.org/showthread.php/518077-build-libqtxdg-and-private-qicon_p-h

Any thoughts?

**Comment by luis-pereira** [comment]
@r-a-v-a-s This seems to be a downstream packaging/installation issue. I don't use openSuse, I really don't know how to help you.
p.s. Make sure you don't have the `QTDIR` pointing to a bad place.

**Comment by r-a-v-a-s** [comment]
New updates on that forum...
I needed to: `zypper in libQt5Gui-private-headers-devel`
which produces `/usr/include/qt5/QtGui/5.6.0/QtGui/private/qicon_p.h`

We got there... thanks for your help :sunglasses:

**Comment by r-a-v-a-s** [comment]
I just found the "Installing the dependencies" section way at the bottom of the 'Build from source' article... *after* the  "Building the base libraries" section. >_<

I updated a few openSUSE dependencies, and moved the section above "Building the base libraries".

**Comment by luis-pereira** [comment]
Great.
